### ISSUE TITLE
Redo server limit configuration

### ISSUE THREAD

**Issue by doublebyte1** [byteroad/ogcapi-simple#19]
With the latest pygeoapi version, the [limits object](https://docs.pygeoapi.io/en/latest/configuration.html#limiting-data-responses) is defined in a different way:

```
limits:
    default_items: 10  # applies to vector data
    max_items: 500  # applies to vector data
    max_distance_x: 123  # applies to all datasets
    max_distance_y: 456 # applies to all datasets
    max_distance_units: m  # as per UCUM https://ucum.org/ucum#section-Tables-of-Terminal-Symbols
    on_exceed: error  # one of error, throttle
```

The current way of setting limits in the pygeoapi configuration, is likely giving unexpected results:
https://github.com/byteroad/ogcapi-simple/blob/3aa832bb871e1bf0faaa2a48b83e68a1a0bc2967/pygeoapi/docker.config.yml#L14
